[32m2025-08-25 23:10:54 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6b4d5aa3-3e55-43dc-9fe6-fc40baf53f0b - 29224 - LOGS_CAPTURED - Started capturing logs in process (pid: 29224).
[32m2025-08-25 23:10:54 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6b4d5aa3-3e55-43dc-9fe6-fc40baf53f0b - 29224 - datos_procesados - STEP_START - Started execution of step "datos_procesados".
[32m2025-08-25 23:10:54 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6b4d5aa3-3e55-43dc-9fe6-fc40baf53f0b - datos_procesados - Loading file from: /workspaces/COVID3/.dagster/storage/datos_limpios using PickledObjectFilesystemIOManager...
[32m2025-08-25 23:10:54 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6b4d5aa3-3e55-43dc-9fe6-fc40baf53f0b - 29224 - datos_procesados - LOADED_INPUT - Loaded input "datos_limpios" using input manager "io_manager", from output "result" of step "datos_limpios"
[32m2025-08-25 23:10:54 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6b4d5aa3-3e55-43dc-9fe6-fc40baf53f0b - 29224 - datos_procesados - STEP_INPUT - Got input "datos_limpios" of type "DataFrame". (Type check passed).
[32m2025-08-25 23:10:54 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6b4d5aa3-3e55-43dc-9fe6-fc40baf53f0b - 29224 - datos_procesados - STEP_OUTPUT - Yielded output "result" of type "DataFrame". (Type check passed).
Exception while writing logger call to event log: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO event_logs (run_id, event, dagster_event_type, timestamp, step_key, asset_key, partition) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('6b4d5aa3-3e55-43dc-9fe6-fc40baf53f0b', '{"__class__": "EventLogEntry", "dagster_event": null, "error_info": null, "level": 10, "message": "", "pipeline_name": "__ASSET_JOB", "run_id": "6b4d ... (81 characters truncated) ... 756163454.7688751, "user_message": "Writing file at: /workspaces/COVID3/.dagster/storage/datos_procesados using PickledObjectFilesystemIOManager..."}', None, '2025-08-25 23:10:54.768875', 'datos_procesados', None, None)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[32m2025-08-25 23:11:00 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6b4d5aa3-3e55-43dc-9fe6-fc40baf53f0b - datos_procesados - Writing file at: /workspaces/COVID3/.dagster/storage/datos_procesados using PickledObjectFilesystemIOManager...
[32m2025-08-25 23:11:00 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6b4d5aa3-3e55-43dc-9fe6-fc40baf53f0b - 29224 - datos_procesados - ASSET_MATERIALIZATION - Materialized value datos_procesados.
[32m2025-08-25 23:11:00 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6b4d5aa3-3e55-43dc-9fe6-fc40baf53f0b - 29224 - datos_procesados - HANDLED_OUTPUT - Handled output "result" using IO manager "io_manager"
[32m2025-08-25 23:11:00 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6b4d5aa3-3e55-43dc-9fe6-fc40baf53f0b - 29224 - datos_procesados - STEP_SUCCESS - Finished execution of step "datos_procesados" in 6.16s.
